# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 16:59
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipos_areas', '0001_initial'),
        ('tipos_areas_funcionales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sedes', '0003_auto_20161005_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('nombre_host', models.CharField(max_length=255)),
                ('direccion_ip', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address])),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('ultimo_nombre_host', models.CharField(max_length=255)),
                ('ultimo_direccion_ip', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address])),
                ('sector', models.CharField(blank=True, max_length=20, null=True)),
                ('zona_secccion', models.CharField(blank=True, max_length=20, null=True)),
                ('pabellon', models.CharField(blank=True, max_length=20, null=True)),
                ('bloque', models.CharField(blank=True, max_length=20, null=True)),
                ('pasadizo', models.CharField(blank=True, max_length=20, null=True)),
                ('torre', models.CharField(blank=True, max_length=20, null=True)),
                ('edificio', models.CharField(blank=True, max_length=20, null=True)),
                ('departamento', models.CharField(blank=True, max_length=20, null=True)),
                ('apartamento', models.CharField(blank=True, max_length=20, null=True)),
                ('piso', models.CharField(blank=True, max_length=20, null=True)),
                ('interior', models.CharField(blank=True, max_length=20, null=True)),
                ('cuadra', models.CharField(blank=True, max_length=20, null=True)),
                ('manzana', models.CharField(blank=True, max_length=20, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('etapa', models.CharField(blank=True, max_length=20, null=True)),
                ('lote', models.CharField(blank=True, max_length=20, null=True)),
                ('sub_lote', models.CharField(blank=True, max_length=20, null=True)),
                ('kilometro', models.CharField(blank=True, max_length=20, null=True)),
                ('denominacion', models.CharField(blank=True, max_length=255, null=True)),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre', models.CharField(db_index=True, help_text='Escribir el nombre del área.', max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)])),
                ('siglas', models.CharField(db_index=True, max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(10)])),
                ('email', models.EmailField(db_index=True, max_length=100, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Correo electrónico (Institucional)')),
                ('fax_interno', models.CharField(blank=True, help_text='(Opcional).', max_length=20, null=True, verbose_name='Fax (Interno)')),
                ('anexo_interno', models.CharField(blank=True, help_text='(Opcional).', max_length=20, null=True, verbose_name='Anexo (Interno)')),
                ('mision', models.TextField(blank=True, help_text='(Opcional)', null=True, verbose_name='Misión')),
                ('vision', models.TextField(blank=True, help_text='(Opcional)', null=True, verbose_name='Visión')),
                ('logotipo', models.ImageField(blank=True, null=True, upload_to='logotipos_areas')),
                ('fecha_creacion', models.DateField(blank=True, null=True, verbose_name='Fecha creación')),
                ('fecha_cese', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, help_text='(Opcional)', null=True, verbose_name='Descripción')),
                ('observacion', models.TextField(blank=True, help_text='(Opcional)', null=True, verbose_name='Observación')),
                ('activo', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True)),
                ('area_dependiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_areas_dependientes_related', to='areas.Area')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedes.Sede')),
                ('tipo_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipos_areas.TipoArea')),
                ('tipo_area_funcional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipos_areas_funcionales.TipoAreaFuncional')),
                ('ultimo_usuario_editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_area_related', to=settings.AUTH_USER_MODEL)),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
                'db_table': 'Areas',
                'verbose_name_plural': 'Areas',
                'verbose_name': 'Area',
            },
        ),
    ]
