# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-05 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_auto_20161105_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='bloque',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='denominacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Denominación'),
        ),
        migrations.AddField(
            model_name='area',
            name='edificio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='interior',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='pabellon',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Pabellón'),
        ),
        migrations.AddField(
            model_name='area',
            name='pasadizo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='piso',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='referencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='sector',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='torre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='zona_secccion',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Zona (Sección)'),
        ),
    ]
