# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0004_auto_20161005_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='referencia',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
