# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0005_auto_20161008_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='referencia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
