# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-20 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0007_auto_20161018_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ('siglas', 'nombre'), 'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
    ]
