# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-21 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0008_auto_20161020_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ('tipo_area', 'nombre'), 'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
    ]
