# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 04:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distritos', '0004_auto_20161003_2304'),
        ('entidades', '0006_auto_20161003_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('nombre_host', models.CharField(max_length=255)),
                ('direccion_ip', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address])),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('ultimo_nombre_host', models.CharField(max_length=255)),
                ('ultimo_direccion_ip', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address])),
                ('sector', models.CharField(blank=True, max_length=20, null=True)),
                ('zona_secccion', models.CharField(blank=True, max_length=20, null=True)),
                ('pabellon', models.CharField(blank=True, max_length=20, null=True)),
                ('bloque', models.CharField(blank=True, max_length=20, null=True)),
                ('pasadizo', models.CharField(blank=True, max_length=20, null=True)),
                ('torre', models.CharField(blank=True, max_length=20, null=True)),
                ('edificio', models.CharField(blank=True, max_length=20, null=True)),
                ('departamento', models.CharField(blank=True, max_length=20, null=True)),
                ('apartamento', models.CharField(blank=True, max_length=20, null=True)),
                ('piso', models.CharField(blank=True, max_length=20, null=True)),
                ('interior', models.CharField(blank=True, max_length=20, null=True)),
                ('cuadra', models.CharField(blank=True, max_length=20, null=True)),
                ('manzana', models.CharField(blank=True, max_length=20, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('etapa', models.CharField(blank=True, max_length=20, null=True)),
                ('lote', models.CharField(blank=True, max_length=20, null=True)),
                ('sub_lote', models.CharField(blank=True, max_length=20, null=True)),
                ('kilometro', models.CharField(blank=True, max_length=20, null=True)),
                ('denominacion', models.CharField(blank=True, max_length=255, null=True)),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre', models.CharField(db_index=True, help_text='Escribir el nombre de la sede.', max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)])),
                ('nombre_direccion', models.CharField(db_index=True, help_text='Escribir nombre de la dirección.', max_length=255, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)], verbose_name='Nombre dirección')),
                ('observacion_direccion', models.TextField(blank=True, help_text='(Opcional).', null=True, verbose_name='Observación (Dirección)')),
                ('telefono', models.CharField(blank=True, help_text='Escribir número de teléfono (Opcional).', max_length=30, null=True, verbose_name='Télefono')),
                ('fax', models.CharField(blank=True, help_text='Escribir número de fax (Opcional).', max_length=30, null=True)),
                ('email', models.EmailField(db_index=True, max_length=100, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Correo electrónico')),
                ('fecha_creacion', models.DateField(blank=True, null=True, verbose_name='Fecha creación')),
                ('fecha_cese', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, help_text='(Opcional).', null=True, verbose_name='Descripción (Sede)')),
                ('observacion_sede', models.TextField(blank=True, help_text='(Opcional).', null=True, verbose_name='Observación (Sede)')),
                ('activo', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distritos.Distrito')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidades.Entidad')),
            ],
            options={
                'db_table': 'Sedes',
                'verbose_name': 'Sede',
                'ordering': ('nombre',),
                'verbose_name_plural': 'Sedes',
            },
        ),
    ]
