# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-03 16:08
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complementos_ubicaciones_predios', '0001_initial'),
        ('nucleos_residenciales', '0001_initial'),
        ('sitios_web', '0001_initial'),
        ('tipos_predios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distritos', '0004_auto_20161003_2304'),
        ('entidades', '0007_auto_20161005_1258'),
        ('divisiones_areas_urbanas', '0001_initial'),
        ('vias', '0002_auto_20161003_2304'),
        ('zonas', '0002_auto_20161003_2304'),
        ('ubicaciones_predios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('nombre_host', models.CharField(max_length=255)),
                ('direccion_ip', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address])),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('ultimo_nombre_host', models.CharField(max_length=255)),
                ('ultimo_direccion_ip', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address])),
                ('nombre_zona_via', models.CharField(db_index=True, help_text='Escribir nombre (Zona/Vía).', max_length=255, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)], verbose_name='Nombre')),
                ('numero_letra_asociado_nombre_via', models.CharField(blank=True, max_length=20, null=True)),
                ('prefijo_bis_vial', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_letra_asociado_prefijo_bis_vial', models.CharField(blank=True, max_length=20, null=True)),
                ('cuadrante_vial', models.CharField(blank=True, choices=[('Este', 'Este'), ('Norte', 'Norte'), ('Oeste', 'Oeste'), ('Sur', 'Sur')], max_length=5, null=True)),
                ('numero_via_generadora', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Escribir número vía generadora.', verbose_name='Número de vía generadora')),
                ('numero_via_generadora_asociado_nombre_via', models.CharField(blank=True, max_length=20, null=True)),
                ('prefijo_bis_numero_via_generadora', models.CharField(blank=True, choices=[('Este', 'Este'), ('Norte', 'Norte'), ('Oeste', 'Oeste'), ('Sur', 'Sur')], max_length=20, null=True)),
                ('numero_letra_asociado_prefijo_bis_numero_via_generadora', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_placa', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Escribir número placa.', verbose_name='Número placa')),
                ('cuadrante_via_generadora', models.CharField(blank=True, choices=[('Este', 'Este'), ('Norte', 'Norte'), ('Oeste', 'Oeste'), ('Sur', 'Sur')], max_length=5, null=True)),
                ('nombre_division_area_urbana', models.CharField(db_index=True, help_text='Escribir nombre de la división urbana', max_length=255, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)], verbose_name='Nombre división urbana')),
                ('nombre_nucleo_residencial', models.CharField(db_index=True, help_text='Escribir núcleo residencial', max_length=255, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)], verbose_name='Nombre núcleo residencial')),
                ('identificador_ubicacion_predio', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_predio', models.CharField(db_index=True, help_text='Escribir nombre del predio.', max_length=255, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)], verbose_name='Nombre predio')),
                ('denominacion', models.CharField(blank=True, help_text='(Opcional).', max_length=255, null=True, verbose_name='Denominación')),
                ('referencia', models.TextField(blank=True, help_text='(Opcional).', null=True)),
                ('observacion_via', models.TextField(blank=True, help_text='(Opcional).', null=True, verbose_name='Observación (Vía)')),
                ('nombre', models.CharField(db_index=True, help_text='Escribir el nombre de la sede.', max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)])),
                ('telefono', models.CharField(blank=True, help_text='(Opcional).', max_length=20, null=True, verbose_name='Télefono')),
                ('fax', models.CharField(blank=True, help_text='(Opcional).', max_length=20, null=True)),
                ('email', models.EmailField(db_index=True, max_length=100, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Correo electrónico (Sede)')),
                ('fecha_creacion', models.DateField(blank=True, null=True, verbose_name='Fecha creación')),
                ('fecha_cese', models.DateField(blank=True, null=True)),
                ('descripcion_sede', models.TextField(blank=True, help_text='(Opcional).', null=True, verbose_name='Descripción (Sede)')),
                ('observacion_sede', models.TextField(blank=True, help_text='(Opcional).', null=True, verbose_name='Observación (Sede)')),
                ('activo', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True)),
                ('complemento_ubicacion_predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes_sede_related', to='complementos_ubicaciones_predios.ComplementoUbicacionPredio')),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes_sede_related', to='distritos.Distrito')),
                ('division_area_urbana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes_sede_related', to='divisiones_areas_urbanas.DivisionAreaUrbana')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidades.Entidad')),
                ('nucleo_residencial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes_sede_related', to='nucleos_residenciales.NucleoResidencial')),
                ('sitio_web', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sitios_web.SitioWeb')),
                ('tipo_predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes_sede_related', to='tipos_predios.TipoPredio')),
                ('ubicacion_predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes_sede_related', to='ubicaciones_predios.UbicacionPredio')),
                ('ultimo_usuario_editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes_sede_related', to=settings.AUTH_USER_MODEL)),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('via', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes_sede_related', to='vias.Via')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes_sede_related', to='zonas.Zona')),
            ],
            options={
                'verbose_name': 'Sede',
                'db_table': 'Sedes',
                'verbose_name_plural': 'Sedes',
                'ordering': ('nombre',),
            },
        ),
    ]
