# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-03 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sedes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sede',
            old_name='numero_via_generadora_asociado_nombre_via',
            new_name='numero_letra_asociado_via_generadora',
        ),
    ]
