# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-03 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sedes', '0002_auto_20161103_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sede',
            name='complemento_ubicacion_predio',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='cuadrante_via_generadora',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='cuadrante_vial',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='denominacion',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='distrito',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='division_area_urbana',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='identificador_ubicacion_predio',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='nombre_division_area_urbana',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='nombre_nucleo_residencial',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='nombre_predio',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='nombre_zona_via',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='nucleo_residencial',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='numero_letra_asociado_nombre_via',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='numero_letra_asociado_prefijo_bis_numero_via_generadora',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='numero_letra_asociado_prefijo_bis_vial',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='numero_letra_asociado_via_generadora',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='numero_placa',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='numero_via_generadora',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='observacion_via',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='prefijo_bis_numero_via_generadora',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='prefijo_bis_vial',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='referencia',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='tipo_predio',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='ubicacion_predio',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='via',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='zona',
        ),
    ]
