# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 16:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sedes', '0002_auto_20161003_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sede',
            old_name='descripcion',
            new_name='descripcion_sede',
        ),
        migrations.AlterField(
            model_name='sede',
            name='email',
            field=models.EmailField(db_index=True, max_length=100, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Correo electrónico (Sede)'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='fax',
            field=models.CharField(blank=True, help_text='(Opcional).', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sede',
            name='telefono',
            field=models.CharField(blank=True, help_text='(Opcional).', max_length=20, null=True, verbose_name='Télefono'),
        ),
    ]
