# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-03 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sedes', '0003_auto_20161103_1136'),
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='ubicacion_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ubicaciones.Ubicacion'),
            preserve_default=False,
        ),
    ]
