# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-19 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sedes', '0005_auto_20161008_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='denominacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Denominación'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='pabellon',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Pabellón'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='zona_secccion',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Zona (Sección)'),
        ),
    ]
