# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-05 04:04
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiapositivaWeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('nombre_host', models.CharField(max_length=255)),
                ('direccion_ip', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address])),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('ultimo_nombre_host', models.CharField(max_length=255)),
                ('ultimo_direccion_ip', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address])),
                ('titulo', models.CharField(db_index=True, help_text='Escribir el título de la diapositiva web.', max_length=100, unique=True)),
                ('imagen', models.ImageField(default='default/No_Image_1.png', help_text='Subir imagen de la diapositiva web. (Opcional)', upload_to='imagenes_diapostivas_web')),
                ('descripcion', models.TextField(blank=True, help_text='(Opcional)')),
                ('observacion', models.TextField(blank=True, help_text='(Opcional)')),
                ('ultimo_usuario_editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diapositivas_web_diapositivaweb_related', to=settings.AUTH_USER_MODEL)),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diapositiva Web',
                'ordering': ('titulo',),
                'db_table': 'Diapositivas_Web',
                'verbose_name_plural': 'Diapositivas Webs',
            },
        ),
    ]
