# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-05 04:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diapositivas_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diapositivaweb',
            options={'ordering': ('titulo',), 'verbose_name': 'Diapositiva Web', 'verbose_name_plural': 'Diapositivas Web'},
        ),
    ]
