# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diapositivas_web', '0002_auto_20160904_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diapositivaweb',
            name='imagen',
            field=models.ImageField(help_text='Subir imagen de la diapositiva web. (Opcional)', upload_to='imagenes_diapostivas_web'),
        ),
    ]
