# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 01:54
from __future__ import unicode_literals

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('diapositivas_web', '0003_auto_20160905_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='diapositivaweb',
            name='archivo',
            field=models.FileField(blank=True, upload_to='archivos_articulos_web'),
        ),
        migrations.AddField(
            model_name='diapositivaweb',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
