# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-04 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='numero_letra_asociado_nombre_via',
        ),
        migrations.AddField(
            model_name='empleado',
            name='numero_letra_asociado_nombre_zona_via',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número|Letra - Asociado Zona - Vía'),
        ),
    ]
