# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-04 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_auto_20161104_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='numero_letra_asociado_via_generadora',
            new_name='numero_letra_asociado_numero_via_generadora',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cuadrante_via_generadora',
            field=models.CharField(blank=True, choices=[('Este', 'Este'), ('Norte', 'Norte'), ('Oeste', 'Oeste'), ('Sur', 'Sur')], default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cuadrante_vial',
            field=models.CharField(blank=True, choices=[('Este', 'Este'), ('Norte', 'Norte'), ('Oeste', 'Oeste'), ('Sur', 'Sur')], default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='numero_letra_asociado_nombre_via',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número Letra Asociado Nombre (Zona/Vía)'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='numero_letra_asociado_prefijo_bis_vial',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número Letra - Prefijo Bis Vial'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='prefijo_bis_numero_via_generadora',
            field=models.CharField(blank=True, choices=[('Bis', 'Bis'), ('No Bis', 'No Bis')], max_length=20, null=True, verbose_name='Número Letra - Número Vía Generadora'),
        ),
    ]
