# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 01:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_auto_20161006_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fotografia',
            field=models.ImageField(blank=True, help_text='Subir fotografia (Opcional).', null=True, upload_to='fotografia_persona', verbose_name='Fotografía'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='Masculino', max_length=9, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='hijo',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Si')], default=False, verbose_name='¿Hijo(s)?'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='numero_hijo',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Escribir número(s) de hijo(s).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Número de hijo(s)'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='referencia',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='tipo_persona',
            field=models.CharField(choices=[('Natural', 'Natural'), ('Jurídica', 'Jurídica')], default='Natural', help_text='Seleccionar tipo de persona.', max_length=8),
        ),
    ]
