# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-04 17:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complementos_ubicaciones_predios', '0001_initial'),
        ('ubicaciones_predios', '0001_initial'),
        ('empleados', '0004_auto_20161104_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='identificador_ubicacion_predio',
            new_name='identificador_ubicacion_tipo_predio',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='numero_letra_complemento_ubicacion_predio',
            new_name='numero_letra_complemento_ubicacion_tipo_predio',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='complemento_ubicacion_predio',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='nombre_predio',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='ubicacion_predio',
        ),
        migrations.AddField(
            model_name='empleado',
            name='complemento_ubicacion_tipo_predio',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleados_empleado_related', to='complementos_ubicaciones_predios.ComplementoUbicacionPredio'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nombre_tipo_predio',
            field=models.CharField(db_index=True, default='', help_text='Escribir nombre del predio.', max_length=255, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)], verbose_name='Nombre tipo predio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='ubicacion_tipo_predio',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleados_empleado_related', to='ubicaciones_predios.UbicacionPredio'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='division_area_urbana',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleados_empleado_related', to='divisiones_areas_urbanas.DivisionAreaUrbana'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nucleo_residencial',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleados_empleado_related', to='nucleos_residenciales.NucleoResidencial'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='numero_letra_asociado_nombre_via',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='N° Letra - Nombre (Zona/Vía)'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='numero_letra_asociado_numero_via_generadora',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='N° Letra - N° vía generadora'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='numero_letra_asociado_prefijo_bis_numero_via_generadora',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='N° Letra - Pref. Bis N° vía generadora'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='numero_letra_asociado_prefijo_bis_vial',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='N° Letra - Pref. Bis vial'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='numero_via_generadora',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Escribir N° vía generadora.', verbose_name='N° vía generadora'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='prefijo_bis_numero_via_generadora',
            field=models.CharField(blank=True, choices=[('Bis', 'Bis'), ('No Bis', 'No Bis')], max_length=20, null=True, verbose_name='Pref. Bis N° vía generadora'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='prefijo_bis_vial',
            field=models.CharField(blank=True, choices=[('Bis', 'Bis'), ('No Bis', 'No Bis')], max_length=20, null=True, verbose_name='Pref. Bis vial'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='tipo_predio',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleados_empleado_related', to='tipos_predios.TipoPredio'),
        ),
    ]
