# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-04 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_auto_20161104_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='identificador_ubicacion_tipo_predio',
            new_name='identificador_ubicacion_predio',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='ubicacion_tipo_predio',
            new_name='ubicacion_predio',
        ),
    ]
