# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-26 16:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_auto_20161008_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='fotografia',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='denominacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Denominación'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_fin_contratacion',
            field=models.DateField(blank=True, help_text='Seleccionar fecha de final de contratación del empleado.', null=True, verbose_name='Fecha fin contratación'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_inicio_contratacion',
            field=models.DateField(help_text='Seleccionar fecha de inicio de contratación del empleado.', verbose_name='Fecha inicio contratación'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='grado_instruccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grados_instrucciones.GradoInstruccion', verbose_name='Grado instrucción'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='numero_hijo',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Escribir número(s) de hijo(s).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Número de hijo(s)'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='ocupacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocupaciones.Ocupacion', verbose_name='Ocupación'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='pabellon',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Pabellón'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='profesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesiones.Profesion', verbose_name='Profesión'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='zona_secccion',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Zona (Sección)'),
        ),
    ]
