# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-29 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import infos_sistemas.validators


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_auto_20161026_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fotografia',
            field=models.ImageField(blank=True, default='default/No_Avatar_1.png', help_text='Subir fotografia (Opcional).', null=True, upload_to='fotografias', validators=[infos_sistemas.validators.valid_extension], verbose_name='Avatar (Fotografía)'),
        ),
    ]
