# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-20 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_auto_20161018_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fecha_fin_contratacion',
            field=models.DateField(blank=True, help_text='Seleccionar fecha de final de contratación del empleado.', null=True, verbose_name='Fecha fin contratación'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_inicio_contratacion',
            field=models.DateField(help_text='Seleccionar fecha de inicio de contratación del empleado.', verbose_name='Fecha inicio contratación'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='grado_instruccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grados_instrucciones.GradoInstruccion', verbose_name='Grado instrucción'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='ocupacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocupaciones.Ocupacion', verbose_name='Ocupación'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='profesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesiones.Profesion', verbose_name='Profesión'),
        ),
    ]
