# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redes_sociales', '0002_auto_20160901_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='redsocial',
            name='imagen',
            field=models.ImageField(blank=True, default='default/No_Image_1.png', help_text='Subir imagen. (Opcional)', null=True, upload_to='imagenes_redes_sociales'),
        ),
    ]
