# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-26 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import infos_sistemas.validators


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Subir fotografia (Opcional).', null=True, upload_to='avatar_usuario', validators=[infos_sistemas.validators.valid_extension], verbose_name='Avatar (Fotografía)'),
        ),
    ]
