# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 04:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionWeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('nombre_host', models.CharField(max_length=255)),
                ('direccion_ip', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address])),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('ultimo_nombre_host', models.CharField(max_length=255)),
                ('ultimo_direccion_ip', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address])),
                ('nombre', models.CharField(db_index=True, help_text='Escribir nombre de la sección web.', max_length=100, unique=True)),
                ('banner', models.ImageField(blank=True, help_text='Subir banner. (Opcional)', upload_to='imagenes_secciones_web')),
                ('archivo_video', models.FileField(blank=True, upload_to='archivos_secciones_web')),
                ('descripcion', models.TextField(blank=True, help_text='(Opcional)')),
                ('observacion', models.TextField(blank=True, help_text='(Opcional)')),
            ],
            options={
                'db_table': 'Secciones_Web',
                'verbose_name': 'Sección Web',
                'ordering': ('nombre',),
                'verbose_name_plural': 'Secciones Web',
            },
        ),
    ]
