# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-02 04:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clases_entidades', '0001_initial'),
        ('documentos_identificaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('nombre_host', models.CharField(max_length=255)),
                ('direccion_ip', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address])),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('ultimo_nombre_host', models.CharField(max_length=255)),
                ('ultimo_direccion_ip', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address])),
                ('nombre', models.CharField(db_index=True, help_text='Escribir el nombre de la entidad.', max_length=255, unique=True)),
                ('siglas', models.CharField(max_length=25)),
                ('numero_documento_identificacion', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Número documento identificación')),
                ('mision', models.TextField(blank=True, help_text='(Opcional)', null=True, verbose_name='Misión')),
                ('vision', models.TextField(blank=True, help_text='(Opcional)', null=True, verbose_name='Visión')),
                ('logotipo', models.ImageField(blank=True, default='default/No_Image_1.png', null=True, upload_to='logotipos_entidades')),
                ('fecha_creacion', models.DateField(blank=True, null=True, verbose_name='Fecha creación')),
                ('fecha_cese', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, help_text='(Opcional)', null=True, verbose_name='Descripción')),
                ('observacion', models.TextField(blank=True, help_text='(Opcional)', null=True, verbose_name='Observación')),
                ('activo', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True)),
                ('clase_entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases_entidades.ClaseEntidad')),
                ('documento_identificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos_identificaciones.DocumentoIdentificacion', verbose_name='Documento identificación')),
            ],
            options={
                'verbose_name': 'Entidad',
                'ordering': ('nombre',),
                'verbose_name_plural': 'Entidades',
                'db_table': 'Entidades',
            },
        ),
    ]
