# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-02 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipos_entidades', '0001_initial'),
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='tipo_entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipos_entidades.TipoEntidad'),
        ),
    ]
