# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0003_auto_20160901_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='slogan',
            field=models.CharField(db_index=True, default='', help_text='Escribir el slogan de la entidad.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entidad',
            name='logotipo',
            field=models.ImageField(blank=True, null=True, upload_to='logotipos_entidades'),
        ),
    ]
