# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0004_auto_20160905_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='slogan',
            field=models.CharField(blank=True, db_index=True, help_text='Escribir el slogan de la entidad.', max_length=255, null=True),
        ),
    ]
