# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 17:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0006_auto_20161003_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='siglas',
            field=models.CharField(db_index=True, max_length=10, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
