# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 04:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloWeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('nombre_host', models.CharField(max_length=255)),
                ('direccion_ip', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address])),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('ultimo_nombre_host', models.CharField(max_length=255)),
                ('ultimo_direccion_ip', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address])),
                ('titulo', models.CharField(db_index=True, help_text='Escribir nombre del articulo web.', max_length=255, unique=True)),
                ('slogan', models.CharField(db_index=True, max_length=255, unique=True)),
                ('imagen', models.ImageField(blank=True, default='default/No_Image_1.png', help_text='Subir imagen del tipo de articulo web. (Opcional)', upload_to='imagenes_articulos_web')),
                ('video', embed_video.fields.EmbedVideoField(blank=True)),
                ('descripcion', models.TextField(blank=True, help_text='(Opcional)')),
                ('observacion', models.TextField(blank=True, help_text='(Opcional)')),
                ('activo', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True)),
                ('fecha_publicacion', models.DateField(blank=True, null=True, verbose_name='Fecha publicación')),
            ],
            options={
                'db_table': 'Articulos_Web',
                'verbose_name': 'Articulo Web',
                'ordering': ('titulo',),
                'verbose_name_plural': 'Articulos Web',
            },
        ),
    ]
