# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 04:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secciones_web', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tipos_articulos_web', '0002_auto_20161003_2304'),
        ('articulos_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articuloweb',
            name='seccion_web',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secciones_web.SeccionWeb'),
        ),
        migrations.AddField(
            model_name='articuloweb',
            name='tipos_articulo_web',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipos_articulos_web.TipoArticuloWeb'),
        ),
        migrations.AddField(
            model_name='articuloweb',
            name='ultimo_usuario_editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos_web_articuloweb_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articuloweb',
            name='usuario_creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
