# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos_modulos_menus_sub_menus', '0002_auto_20161003_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogomodulomenusubmenu',
            name='descripcion',
            field=models.TextField(blank=True, help_text='(Opcional)', null=True, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='catalogomodulomenusubmenu',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Subir imagen. (Opcional)', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='catalogomodulomenusubmenu',
            name='observacion',
            field=models.TextField(blank=True, help_text='(Opcional)', null=True, verbose_name='Descripción'),
        ),
    ]
