# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-04 13:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='nombre_zona_via',
            field=models.CharField(db_index=True, help_text='Escribir nombre (Zona/Vía).', max_length=255, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)], verbose_name='Nombre (Zona/Vía)'),
        ),
    ]
